spring:
  boot:
    admin:
      client:
        url: http://localhost:8092   # Admin Server URL
      instance:
        service-base-url: http://localhost:8080
      notify:
        enabled: false 

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,circuitbreakerevents,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true