spring:
  application:
    name: microservice8
server:
  port: 8088


eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:microservice-8}
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka1:9091/eureka/,http://eureka2:9092/eureka/,http://eureka3:9093/eureka/}