server:
  port: 8088


eureka:
  instance:
    metadata-map:
      version: 1.0.0
      env: dev
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka1:9091/eureka/,http://eureka2:9092/eureka/,http://eureka3:9093/eureka/}