
server:
  port: 0

eureka:
  instance:
    #appname: micro6-client
    metadata-map:
      version: 1.0.0
      env: dev
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
